on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set lower case repository environment variable
        env:
          REPOSITORY: "${{ github.repository }}"
        run: echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Dev Container and Run CI checks
        uses: ./.github/actions/devcontainer
        env:
          REPOSITORY_LC: ${{ env.REPOSITORY_LC }}
        with:
          cache_image_name: ghcr.io/${{ env.REPOSITORY_LC }}/devcontainer
          run_command: pnpm check
